### ISSUE TITLE
mkdocstrings automatically sorts members of class

### ISSUE THREAD

**Issue by rossmechanic** [mkdocstrings/mkdocstrings#114]
When adding a class to be documented using mkdocstrings, all the members are rendered alphabetically. I'd prefer to render them based on the order in which they're defined in code. Any idea how to override the sorting? Can't seem to figure out where it's happening

**Comment by pawamoy** [comment]
They are sorted in the template: https://github.com/pawamoy/mkdocstrings/blob/master/src/mkdocstrings/templates/python/material/children.html#L19 and similar lines.

Along with #102, we could implement the usual Sphinx's options: source order, alphabetical order, specified order (using `members`), and group + alphabetical order.

**Comment by rossmechanic** [comment]
Feature works for me! Literally just found the sorting in the template. For the time being, I'm overwriting the template.

**Comment by chbndrhnns** [comment]
I would love to see a sorting order by type, like classmethods come after instance methods.

**Comment by Uzay-G** [comment]
+1 for the sorting by code order.

**Comment by camold** [comment]
+1 for the sorting by code order

**Comment by lluar** [comment]
+1 for the sorting by code order

**Comment by oprypin** [comment]
(just commenting on implementation)
I think the template shouldn't sort anything, it should receive items in sorted order already. I'd also agree (https://github.com/pawamoy/pytkdocs/issues/29) that *pytkdocs* shouldn't sort anything itself -- just post-process that in code rather than letting the template do it.
BTW it's also not a requirement for pytkdocs to return items in code order, it could just add code location as a field, and then these items could be sorted by that key here.

**Comment by pawamoy** [comment]
Yup, I agree. pytkdocs can add the starting line number in the data it generates.

**Comment by yanqd0** [comment]
It will be a better design to sort by code order by default. In fact, the order may be already considered by the author.

Providing some other sorting methods is good, but optional.

**Comment by kenimou** [comment]
+1 for the sorting by code order. Don't want static methods/util functions to mix up with more important functions. Thanks!

**Comment by pawamoy** [comment]
Implemeted in #274
