### ISSUE TITLE
Leverage Python for complex configuration

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/mkdocstrings#131]
Some users expressed the need for complex filtering / rendering. I feel like these requests will increase over time, as we will likely support more specific objects like Pydantic/Marshmallow/Django models, and that it will be harder and harder to define clean and powerful configuration options for selecting objects and their members, and for rendering them.

To address this, I would like to leverage the power of Python. In `mkdocstrings`, the idea is to let the users write their own Jinja filters (and more). In `pytkdocs`, the idea is to let the users define their own selection/filtering/ordering logic (and more).

Several issues here would benefit (or have benefited) from such a feature:

- Respect the order of selection.members #102
- Can I collect classes for documentation based on a custom function? #111
- Add ability to load library (like Django) before running #89
- Configuration for pytkdocs `filter` option? #62
- mkdocstrings automatically sorts members of class #114
- Remove path on parameter annotation #115 (mention of filters)
- Formatting objects differently depending on their inheritance #130
- Void built-in docstrings #16
- Add option not to display the root group header if it's the only group #17
- "Show source code in..." should be more subtle #35
- Enhancement: Separate Properties and class variables #76

...and some more in pytkdocs repository.

Before starting to think about implementation details, we should list the things we want to be able to configure.
Based on the above issues:

- rendering
  - members ordering
  - custom rendering for specific types of objects
  - various modifications on template variables (with Jinja filters)
- selection
  - complex selection (using category, name, path, parent classes, properties of objects, etc.)
  - modification of data during collection 
- global setup and teardown code (Django setup, mocking libraries, etc.). For this we already have `setup_commands`, but maybe there's a way to add it back in this spec
- local setup and teardown code?

What else :slightly_smiling_face: ?

Then, once we know what we want, we can think about solutions:
- methods to register code?
- hooks in mkdocstrings and pytkdocs?
- ...?

Please share your thoughts :smile:

**Comment by adunmore** [comment]
+1 for more/more granular selection rules. I just ran into a use case where it would be nice to filter objects by category.

Following this issue for when it's time to start work :)

**Comment by AXGKl** [comment]
I have the problem that I'm bascially using your python handler and patch the `rebuild_category_lists` with mine, in order to inject custom content (e.g. svgs) created while my code was running during pytest. 
I cannot do this in jinja templates, need to really run python for finding images and copy them over into the docs tree.

Problem: There I cannot get a hold on the config. E.g. I need the path of the respective markdown page where the triggering identifier is (in order to know where to copy images to) - but checking the `extension.py` it seems you throw the whole config from yaml away, except 'selection' and 'rendering' sections. If I add a custom key to selection then I get: `mkdocstrings.handlers.CollectionError: __init__() got an unexpected keyword argument `base_path'`

=> A passing of custom config outside of those 2 keys would be appreciated, then custom code for enriching the pytkdocs results would have superpowers ;-)

**Comment by pawamoy** [comment]
This is outdated. I'm not planning on moving to Python configuration.
