### ISSUE TITLE
Document variable default value

### ISSUE THREAD

**Issue by hoechenberger** [mkdocstrings/mkdocstrings#177]
Hello, I've searched the issue tracker and documentation of `mkdocstrings` and `pytkdocs` and couldn't really find an answer to my question. If I have overlooked something, I'd appreciate if you could point me to a solution.

So I have a Python module that defines a number of global variables like:
```python
interactive: bool = False
"""
If True, the scripts will provide some interactive elements, such as
figures. ...
"""
```

This is rendered as:
![Screenshot 2020-11-03 at 10 06 09](https://user-images.githubusercontent.com/2046265/97966570-4b574600-1dbc-11eb-8c34-ef769bac219e.png)

I'd like to display the default value (in this case, `False`) as well. What's the recommended method to do so?

Thank you very much for your help,

Richard

**Comment by pawamoy** [comment]
That's not possible yet. I'm tracking this in this pytkdocs issue: https://github.com/pawamoy/pytkdocs/issues/64

**Comment by hoechenberger** [comment]
Thank you for pointing me to the correct place, @pawamoy!
Maybe it makes sense to leave this issue open so others will easily get this info as well. Otherwise, feel free to close.

**Comment by pawamoy** [comment]
The [new handler](https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers)'s [data collector](https://mkdocstrings.github.io/griffe/) is able to pick up attribute values, and the templates will display them :slightly_smiling_face: 
I'll close this issue since I'm not willing to add support for this in the legacy handler (pytkdocs). Feel free to ask for reopening it if someone wants to send PRs to pytkdocs!
