### ISSUE TITLE
Printing some memory register of callback function

### ISSUE THREAD

**Issue by bitnom** [mkdocstrings/mkdocstrings#180]
Rendered:
```python
apply_if(func_to_apply: Callable, var: Any, condition: Callable, else_func: Callable = <function do_nothing at 0x7f93d9006dc0>) -> Any
```

from the code: https://github.com/TensorTom/datafunc/blob/master/datafunc/__init__.py

**screenshot:**

![bug](https://i.imgur.com/aXJJsmp.png)

**Comment by pawamoy** [comment]
There's not much `pytkdocs` can do here. If you have control over the `else_func` object class, you should add `__str__` and `__repr__` methods to it to improve the display in mkdocstrings.

I'm gonna close since nothing can be done on mkdocstrings side, but feel to reopen if I missed something :slightly_smiling_face: !

**Comment by pawamoy** [comment]
I realize now that `else_func` really is a function, so there's no way to provide a custom representation of it on the user side. Maybe we could get rid of the memory address indeed. Or maybe you have a suggestion on what we should render instead of `<function do_nothing at 0x...>`?

**Comment by oprypin** [comment]
I guess pytkdocs could certainly check `if isinstance(obj, types.FunctionType): use(obj.__name__)` - but that's a very situational workaround, as it doesn't apply recursively and doesn't apply to other objects that have an address.

**Comment by corykinney** [comment]
I'm encountering a similar issue, but my default value is a ThermoPhase object from [Cantera](github.com/cantera/cantera) which then shows up as a memory address. It'd be nice if there was a way to override that, as I can't simply add a `__str__` or `__repr__` method easily.

**Comment by pawamoy** [comment]
The [new Python handler](https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers) visits the code's AST, so parameters with functions (or other `str()`-unfriendly objects) will be displayed as they are written in the code rather than with their memory address. Not closing because in some cases inspection is still necessary and memory addresses will appear again, and we should do something about it.
