### ISSUE TITLE
Is there a way to parse docstrings in Cython (.pyx) files ?

### ISSUE THREAD

**Issue by farjasju** [mkdocstrings/mkdocstrings#221]
I have a Cython module that I can import this way : `import cython_module`.
Its source code is in a *cython_module.pyx* file, at the same level of other *.py* files that already work well with mkdocstrings:
```
.
├── cython_module.pyx
├── predict.py
├── setup.py
└── etc
```
This cython module contains a class with a docstring:
```python
cdef class Model:
    """
    This is the lower-level class used for inference, it stores the model in an optimized way and features a predict method.

    Attributes:
        trees : The array of trees composing the model.
        nb_trees : The number of trees in the model.
    """

    cdef Tree* trees
    cdef uint16_t nb_trees
```
When specifying a `::: cython_module` in one of the .md files, I get this warning: `WARNING -  mkdocstrings.handlers.python: Couldn't read source for 'cython_module': source code not available`, and in the generated doc, the only thing showed after "cython_module" is the class name ("Model"), but no docstring, nor attributes.

Is there a way to generate documentation from docstrings in Cython files/modules ?

Thanks!

**Comment by pawamoy** [comment]
Could this be:

```python
from Cython.Compiler import Options

# Preserve `__doc__` on functions and classes
# http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#compiler-options
Options.docstrings = True
```

?

**Comment by suned** [comment]
Generally speaking `inspect` doesn't play nice with Cython. for example, if you try to call `inspect.getsource` on a Cython function, you'll get a `TypeError`: `TypeError: module, class, method, function, traceback, frame, or code object was expected, got cython_function_or_method`

**Comment by suned** [comment]
This would be fixed by integrating https://github.com/mkdocstrings/pytkdocs/pull/98

**Comment by pawamoy** [comment]
So, do we agree that it would be better integrated with a proper Cython handler?

**Comment by WillDaSilva** [comment]
What's the first step we should take towards making a Cython handler? Would it be a new project under https://github.com/mkdocstrings?

**Comment by WillDaSilva** [comment]
I would expect us to want to use the same rendering settings between Python and Cython within the same project, so instead of a whole new handler, maybe we just want a new collector for Cython. Then we could have some kind of check to see if something being documented comes from Cython, and if so, use the Cython collector instead of the Python collector. In both cases the Python handler would be used.

Would something like this be possible?

**Comment by pawamoy** [comment]
(memo for myself, will answer later)

Maybe possible to parse Cython code with this instead of introspecting it:

- https://github.com/cython/cython/blob/master/Cython/Parser/Grammar
- https://pypi.org/project/antlr-ast/

**Comment by pawamoy** [comment]
Hey @suned, @WillDaSilva, the new collector I created, [griffe](https://github.com/pawamoy/griffe), is able to find and inspect .so and .pyd files, which would be the compiled version of your .pyx files. Would it be enough for you? It would require to actually compile your .pyx files (by "installing" your package I guess, passing through setup.py) so that griffe can inspect the compiles modules. Or maybe you really need to extract data from the .pyx files themselves?

It would be very helpful if you could try griffe on one of your Cython projects. Or maybe share a link to such a project so that I can try it myself :slightly_smiling_face:

**Comment by pawamoy** [comment]
Also, @WillDaSilva, sorry for the late answers:

> What's the first step we should take towards making a Cython handler? Would it be a new project under https://github.com/mkdocstrings?



Sure, either create the project in your own account and we transfer it to mkdocstrings once it's ready, or we can directly create it in mkdocstrings org and I give you necessary permissions.

> I would expect us to want to use the same rendering settings between Python and Cython within the same project, so instead of a whole new handler, maybe we just want a new collector for Cython. Then we could have some kind of check to see if something being documented comes from Cython, and if so, use the Cython collector instead of the Python collector. In both cases the Python handler would be used.
Would something like this be possible?

That makes sense indeed. Let see if griffe would work for compiled Cython modules first. If it doesn't, the new handler could be enhanced with a cython version that calls a special cython extractor indeed.

**Comment by WillDaSilva** [comment]
@pawamoy That sounds great. I'll try out Griffe on one of my projects that uses Cython. Maybe I could add some test cases to it for Cython too, but we'll worry about that after we can verify that it's working at all.

> It would require to actually compile your .pyx files (by "installing" your package I guess, passing through setup.py) so that griffe can inspect the compiles modules.

A typical workflow for building docs for a Cython project is to install it (e.g. `pip install .`), then run the doc builder (e.g. `sphinx-build ...`, or `mkdocs ...`, etc.), so as far as I understand it, Griffe should work for this. I suspect it will need certain Cython compilation options enabled, such as `linetrace`. I'll play around with it, hopefully today, and let you know what I find.

**Comment by WillDaSilva** [comment]
Looks like several projects created with Cython fail with a `KeyError`. For instance, here is the output from running `griffe pandas`:

```
INFO       Loading package pandas
Traceback (most recent call last):
  File "/home/will/.pyenv/versions/workshop/bin/griffe", line 8, in <module>
    sys.exit(main())
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/cli.py", line 234, in main
    packages = _load_packages(opts.packages, extensions, search, opts.docstyle, opts.docopts)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/cli.py", line 89, in _load_packages
    module = loader.load_module(package, search_paths=search_paths)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/loader.py", line 195, in load_module
    top_module = self._load_module_path(top_module_name, top_module_path, submodules=submodules)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/loader.py", line 275, in _load_module_path
    self._load_submodules(module)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/loader.py", line 280, in _load_submodules
    self._load_submodule(module, subparts, subpath)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/loader.py", line 289, in _load_submodule
    member_parent[subparts[-1]] = self._load_module_path(
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/loader.py", line 273, in _load_module_path
    module = self._inspect_module(module_name, module_path, parent)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/loader.py", line 121, in _inspect_module
    return inspect(
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 78, in inspect
    return Inspector(
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 149, in get_module
    self.inspect(top_node)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 160, in inspect
    super().inspect(node)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/base.py", line 38, in inspect
    getattr(self, f"inspect_{node.kind}", self.generic_inspect)(node)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 207, in inspect_module
    self.generic_inspect(node)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 189, in generic_inspect
    self.inspect(child)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 160, in inspect
    super().inspect(node)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/base.py", line 38, in inspect
    getattr(self, f"inspect_{node.kind}", self.generic_inspect)(node)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 224, in inspect_class
    self.generic_inspect(node)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 189, in generic_inspect
    self.inspect(child)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 160, in inspect
    super().inspect(node)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/base.py", line 38, in inspect
    getattr(self, f"inspect_{node.kind}", self.generic_inspect)(node)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 249, in inspect_method_descriptor
    self.handle_function(node, {"method descriptor"})
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/inspector.py", line 325, in handle_function
    returns = return_annotation and get_annotation(return_annotation, parent=self.current)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/nodes.py", line 669, in get_annotation
    return _get_annotation(node, parent)
  File "/home/will/.pyenv/versions/3.9.6/envs/workshop/lib/python3.9/site-packages/griffe/agents/nodes.py", line 654, in _get_annotation
    return _node_annotation_map[type(node)](node, parent)
KeyError: <class 'str'>
```

However, `griffe` does work on at least some Cython projects! I tried it on [`orderedset`](https://github.com/simonpercivall/orderedset/), and the output seemed fine as far as I could tell. It may be the case that Cython poses no particular issue for Griffe, and these key errors are unrelated. After all, similar issues were observed on some non-Cython projects using Griffe 0.8.0.

**Comment by pawamoy** [comment]
Ah, yes, I'm trying to resolve this issue since yesterday. The thing is: in my own modules, I import future annotations (making them all strings, see PEP 563). But when inspect builds a signature for a function coming from another module that does not import future annotations, its return annotation can be a class like `<class 'int'>`. So I have to deal with actual Python objects instead of a string. It's simple for builtin types like int, str, etc., but I guess the return annotation could also be a very complex annotation. Anyway, maybe I shouldn't try to reparse the annotation (I noticed I actually don't do it for parameters annotations), but then the JSON serialization will probably fail... I'll keep you posted :smile:

**Comment by WillDaSilva** [comment]
Perhaps you can compile the files being documented yourself using https://docs.python.org/3/library/functions.html#compile

That way you could pass in the flag for the annotations future, ensuring that the annotations are always strings.

This would at least require obtaining the paths to the files that are being processed. Additionally, the order in which they are compiled must match the order in which they are imported. This approach might be infeasible, but I figured I ought to share the idea.

Long-term, there is no guarantee that this ability to get annotations as strings will remain in the language. [It is being debated by the Python Steering Council](https://discuss.python.org/t/type-annotations-pep-649-and-pep-563/11363). Presumably there must be some sane way to get the string representations of the annotations from their object forms? I would expect other Python modules that handle annotations, such as MyPy, to also deal with this issue.

**Comment by pawamoy** [comment]
This is indeed what I want to do: compile the *code* into an AST to re-use the utilities I've written for visiting ASTs. But for this, I actually need the string representation of these actual Python objects :smile: Anyway, I think I'll simply go with `annotation.__name__` for builtin types, and `repr(annotation)` for the rest, at least for now. Thanks for sharing ideas :slightly_smiling_face:

**Comment by pawamoy** [comment]
Just pushed griffe 0.9.0 with lots of fixes. It doesn't even crash on a good part of the standard-lib now (maybe all of it?) :smile:

**Comment by WillDaSilva** [comment]
Looks good to me. Works on the Cython projects I can't share, as well as Numpy, Pandas, and more. Great work!

**Comment by pawamoy** [comment]
So, the new Python handler is now available as "experimental". Data can be extracted from compiled modules, so Cython files are covered (given they are compiled and available on `sys.path`). Feel free to further comment on this, closing :slightly_smiling_face:

**Comment by jewaniuk** [comment]
Hello, I have read this thread multiple times and unfortunately still cannot figure out what is going wrong when trying to create documentation for my Cython (.pyx) modules. I am trying to accomplish exactly the same task as @farjasju. I can access the module by inserting `::: quotonic.fock` (corresponds to `fock.cpython-310-darwin.so` as compiled from `fock.pyx`) in my markdown file for the corresponding page, however, when I build the documentation, I get what appears in the images below rather than what I would expect from the docstrings I've placed in my functions in `fock.pyx`. 
![Screenshot 2023-01-17 at 7 11 41 PM](https://user-images.githubusercontent.com/64928185/213040427-f87da985-4cd7-450c-8342-ebeb393f6c7c.png)
![Screenshot 2023-01-17 at 7 11 49 PM](https://user-images.githubusercontent.com/64928185/213040431-e9b49948-9461-4447-b0c9-b35614a2dfa9.png)


I've also tried inserting `::: quotonic.fock.getDim` to access one of the functions directly, yet, this results in the following error:
`ERROR - mkdocstrings: Template 'alias.html' not found for 'python' handler and theme 'material'.`
`ERROR - Error reading page 'fock.md': alias.html`

Please let me know what I am missing here! I apologize for my naïvety.

**Comment by pawamoy** [comment]
You see all the dunder attributes of the module (`__file__`, `__name__`, etc.) because the module is compiled and therefore Griffe (if you're using the new Python handler and not the legacy one) imported it and inspected it. Objects with dunder (double underscore) names are not excluded by default. Try to use the `members` or `filters` options to remove them from the rendered docs.

As for the `template alias.html not found` error, it usually happens when the compiled module "lies" about its `__module__` attribute. If you point me to a repository which I can use to replicate the issue, I'll be happy to investigate :slightly_smiling_face: But please open a new issue first!
