### ISSUE TITLE
Documentation for class attributes using triple-quotes doesn't show up at all

### ISSUE THREAD

**Issue by jmkd3v** [mkdocstrings/mkdocstrings#313]
**Describe the bug**
No documentation is generated for attributes, even when a triple-quoted string is placed underneath it.
Example code where no attributes are generated:
```py
class MyClass:
    def __init__(self):
        self.a = "b"
        """Example"""
```

**To Reproduce**
1. Create a Python class
2. Define an attribute in the __init__
3. Add a triple-quoted string below it
4. No documentation is generated

**Expected behavior**
Documentation would be generated in an Attributes table as stated in the README.

**Information (please complete the following information):**
- `mkdocstrings` version: 0.15.2

**Comment by pawamoy** [comment]
Hi, thanks for the report. Indeed, pytkdocs parses the assignments and triple-quoted strings in the `__init__` method, but then it has no use for them, since these attributes do not appear as members of the class itself, and pytkdocs does not append an Attributes section to the class' docstring either. Not sure what we should do here.

The workaround is of course to add an Attributes section to the class docstring yourself. Annotations in the `__init__` methods will be used in that case.

**Comment by jmkd3v** [comment]
If I'm already adding an Attributes section to the class docstring, is there any use at all for adding these triple-quoted docstrings after the variables? Will it take them and use them in the sections automatically?

**Comment by pawamoy** [comment]
No it will not :confused: It effectively makes attribute docstrings in `__init__` methods useless :confused:

**Comment by jmkd3v** [comment]
> No it will not 😕 It effectively makes attribute docstrings in `__init__` methods useless 😕

Alright, got it 😔 I'll stick with an attributes section for now - thanks for the help!
