### ISSUE TITLE
Add extra text for abstract methods

### ISSUE THREAD

**Issue by ofek** [mkdocstrings/mkdocstrings#349]
**Is your feature request related to a problem? Please describe.**

To clearly indicate subclasses must implement them:

```python
from abc import ABC, abstractmethod

class Interface(ABC):
    @abstractmethod
    def foo(self):
        pass

    @abstractmethod
    def bar(self):
        pass
```

**Describe the solution you'd like**

Just add a `abstract method` kind of like how it does `property readonly` already

**Describe alternatives you've considered**

**Additional context**

I'd recommend only supporting this Python 3.4+ way https://stackoverflow.com/a/13646263

**Comment by pawamoy** [comment]
Version 0.17.0 of Griffe sets an `abstract` label on such methods :slightly_smiling_face: 
If you're using the new Python handler, these labels should already be rendered.
Maybe I should have use `abstractmethod` instead of `abstract` now that I think about it, to be consistent with `staticmethod` and `classmethod`. Let me know what you think. I'll close for now but we can reopen!

**Comment by ofek** [comment]
> Maybe I should have use abstractmethod instead of abstract now that I think about it, to be consistent with staticmethod and classmethod.

That's a good idea!

**Comment by pawamoy** [comment]
OK, will change it to `abstractmethod` then :slightly_smiling_face:
