### ISSUE TITLE
Errors with new python handler 

### ISSUE THREAD

**Issue by LordOfPolls** [mkdocstrings/mkdocstrings#382]
**Describe the bug**
As per #317 im creating an issue for the issues ive come across with migrating to the new python handler. 

- `loader.py`:282 - charmap can't decode character
  - Traceback -  https://pastebin.com/az3MaHL2
  - Resolved by changing `code = module_path.read_text()` -> `code = module_path.read_text("utf-8")`
  - As per https://github.com/mkdocstrings/mkdocstrings/issues/317#issuecomment-103846768, i have checked and the file is UTF-8 encoded 
- `rendering.py`:109 - TypeError: '<' not supported between instances of 'NoneType' and 'int'
  - Traceback - https://pastebin.com/KqV4QgPB
  -  This appears to be caused when mkdocstrings attempts to call pymdownx's highlight method, unsure on resolution as i haven't had chance to dive into it yet

**To Reproduce**
- Uses this repo: https://github.com/Discord-Snake-Pit/Dis-Snek
- Change `docs/requirements.txt` to use the new handler
- Run `mkdocs serve`
- See Errors
  - `loader.py` should be the first error, once you change line 282 you'll see the `rendering.py` error

**Information (please complete the following information):**
- OS: [e.g. iOS] Windows 11
- Browser: [e.g. chrome, safari] NA - Fails before serving
- `mkdocstrings` version: [e.g. 0.10.2] 0.18.0
- `mkdocstrings-python` version: 0.6.0

**Additional context**
NA

**Comment by pawamoy** [comment]
You probably have a different locale on your system, and Python files should always be UTF8 encoded, so I think hard-coding `utf-8` as encoding while reading is the right thing to do, thanks. If reading fails, we can log an error.

**Comment by pawamoy** [comment]
OK, it seems Griffe still has trouble understanding relative imports. I'll use snippets of your code to add some tests and fix this.

**Comment by pawamoy** [comment]
@LordOfPolls, I'm not sure if I want to scream at you, or thank you, because your project gave me a hard time :joy: 
But it helped me to discover *several* bugs in Griffe!

Griffe particularly did not support expanding wildcards recursively. It also had issues with resolving some imports as absolute paths, as well as understanding that a "module member" is not the same as a "submodule" (which possibly shows a design flaw, I'll open a ticket for that). Last thing, I'll have to special case imports under `if TYPE_CHECKING` or `if False` because it means they are not exported and should not be included in wildcards expansion. Phewww :disappointed_relieved: That was quite a debugging session!

So, first: **thank you**. You helped making Griffe better.
Second, and I can't help it: I strongly recommend you not to use wildcards so much. You basically make *every single object of your codebase* available in the `dis_snek` module. Maintaining such a public API must be... challenging. And it's probably error prone. Do you assert there's no object with the same name, anywhere in your code, each time you create a new one? Genuinely curious :joy: 

Anyway, thanks again, and expect some bugfix releases in the next few days :slightly_smiling_face:

**Comment by LordOfPolls** [comment]
Yeah ill completely admit, the import situation with `dis_snek` isnt ideal, we use wildcard imports entirely out of laziness as the project is still in alpha and things are shuffling around a decent amount. It is in our internal todo to sort it out, just incredibly low priority rn. We do combat the wildcard *issues* with dunder all however. 

I very much appreciate your hard work, and feedback.

**Comment by pawamoy** [comment]
I've published new versions of Griffe (0.12.5) and the Python handler (0.6.2). Let me know if they work for you. I'll close this since the issues mentioned here should be fixed. The last thing is tracked here: https://github.com/mkdocstrings/griffe/issues/42

**Comment by LordOfPolls** [comment]
Hi, bit late of a reply, but i've been working on other bits instead of our docs. 

While the above issues are seemingly resolved, the building process enters an infinite loop which eventually ends in a maximum recursion depth exception.

**Comment by pawamoy** [comment]
Hi, no problem! Still the Dis_Snek project? I'll use it to debug. In the meantime you can provide a traceback if you have one :slightly_smiling_face:
