### ISSUE TITLE
Support class variable annotations

### ISSUE THREAD

**Issue by BlueGlassBlock** [mkdocstrings/mkdocstrings#393]
**Is your feature request related to a problem? Please describe.**
Support annotating class annotations can help us show the docs of instance properties. 

**Describe the solution you'd like**
Support the format:
```py
class C:
	  anno: str
	  """This is anno's explaination"""
```

**Describe alternatives you've considered**
Add default value to every class annotation.

**Additional context**

**Comment by pawamoy** [comment]
Are you using the experimental Python handler or the legacy one?

**Comment by BlueGlassBlock** [comment]
I've specified `mkdocstrings[python]` as the dependency, I think it's the experimental one.
![image](https://user-images.githubusercontent.com/50769752/155697722-a62662fc-1893-4327-a5f3-434766272f02.png)

**Comment by BlueGlassBlock** [comment]
Well, it turns out that they are marked as class attributes because I'm using `pydantic`...

Thanks for your time 🤣

**Comment by BlueGlassBlock** [comment]
I found out it only supports the `Attribute` section...

**Comment by pawamoy** [comment]
Pydantic has nothing to do with this :slightly_smiling_face: 
These variables are declared in your class, so they are parsed as class variables/attributes.
I think you wanted a different behavior because you are using Pydantic (showing them as instance attributes maybe?)
This can be implemented with a [Griffe](https://github.com/mkdocstrings/griffe) extension.
Closing as the title is rather confusing (Pydantic support is in my backlog).
