### ISSUE TITLE
Feature: an equivalent to sphinx.ext.doctest

### ISSUE THREAD

**Issue by kevinheavey** [mkdocstrings/mkdocstrings#400]
Sphinx provides the `make doctest` command to run code samples in docs (including docs generated from docstrings). Here is the [documentation](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html) for it but to be honest I don't know what those docs are trying to say, I just run `make doctest` and it works, [example here](https://github.com/kevinheavey/pyheck/blob/main/Makefile#L2).

I use `make doctest` instead of the doctest features in pytest because pytest does not and will not support doctests for native modules written in C, Rust etc (https://github.com/pytest-dev/pytest/issues/9711), and Sphinx seems to be the only solution to this.

If this something you or any contributors decide to implement that would be amazing, as I do not want to use Sphinx 😅

**Comment by pawamoy** [comment]
What does the command do exactly? Just run the snippets to see if there's an assertion error or an exception raised?

**Comment by kevinheavey** [comment]
> What does the command do exactly? Just run the snippets to see if there's an assertion error or an exception raised?

It does check for those, but the main thing is it runs [doctest](https://docs.python.org/3/library/doctest.html), which checks if the examples that start with `>>>` produce the expected output.

Or rather, it runs some low-level doctest functions, because that doctest library doesn't work out of the box with extensions written in C, Rust etc

**Comment by pawamoy** [comment]
If you can provide more technical details on what exactly this `make doctest` command does, we might be able to replicate its behavior. After all, we're still using well known docstring styles whether we're using mkdocs/mkdocstrings or not, so `doctest` at least should already work the same. I'll leave this open for now because we can still discuss about it, but I'd myself consider this out of scope for mkdocstrings (Griffe already goes out of its way to parse docstrings, I really don't think it should also run and check Python snippets in those :sweat_smile: this should be done in an new/external tool).

**Comment by pawamoy** [comment]
I'll close this as out of scope, feel free to comment further.
