### ISSUE TITLE
intersphinx linking does not work with std:label entries but works with py:method ones

### ISSUE THREAD

**Issue by ssbarnea** [mkdocstrings/mkdocstrings#510]
**Describe the bug**

Apparently any entries of type `std:label` from `objects.inv` are purely ignored/not-recognize, making impossible lo link to documentation.

**To Reproduce**

Lets analyze a practical example, https://docs.ansible.com/ansible/latest/objects.inv which can be converted to text for debugging via `sphobjinv convert plain objects.inv objects.txt`.

I will be listing some of the txt output here:

```
Ansible.get_bin_path py:method 1 api/index.html#$ -
developing_galaxy std:label -1 galaxy/dev_guide.html#developing-galaxy Galaxy Developer Guide
```

- Using `[Ansible.get_bin_path][]` works as expected.
- Using `[developing_galaxy][]` does not work and produces, `Could not find cross-reference target '[developing_galaxy]'`

It seems that `std:label` entries are not recognized but `py:method` ones are.

**Expected behavior**

Be able to link any entries from `objects.inv`.

**Information (please complete the following information):**
```
mkdocstrings==0.19.1
mkdocstrings-python==0.8.3
```

**Additional context**

**Comment by ssbarnea** [comment]
In fact it seems that be a little bit different, as I seen also simple entries not being recognized but others being. 

Lets analyze a practical example, https://docs.ansible.com/ansible/latest/objects.inv which can be converted to text for debugging via `sphobjinv convert plain objects.inv objects.txt`.

I will be listing some of the txt output here:

```
Ansible.get_bin_path py:method 1 api/index.html#$ -
developing_galaxy std:label -1 galaxy/dev_guide.html#developing-galaxy Galaxy Developer Guide
```

## Outcomes

- Using `[Ansible.get_bin_path][]` works as expected.
- Using `[developing_galaxy][]` does not work and produces, `Could not find cross-reference target '[developing_galaxy]'`

It seems that `std:label` entries are not recognized but `py:method` ones are.

**Comment by pawamoy** [comment]
Hello, thanks for the investigation and report! Since we claim to support Sphinx inventories, I guess this can be considered a bug indeed.

We can see here that we explicitly filter on `py` domain:

https://github.com/mkdocstrings/python/blob/4ce0fc824fc36cadcf2b70cc72b627bdaa5abd65/src/mkdocstrings_handlers/python/handler.py#L189

...probably because this is done in the Python handler, which has nothing to do with the `std` domain :thinking: 

I'm not against supporting the `std` domain, actually I'm in favor of it, as well as populating the inventories built by mkdocstrings with the reference of headings appearing throughout the docs, but I'm not yet sure how this should be implemented.

**Comment by ssbarnea** [comment]
@pawamoy Thanks for pointing to the code. I think that the "safe" route for this would be to allow use to configure the list of allowed domains, with default to "py".

**Comment by ssbarnea** [comment]
After few minutes looking at the code I realise that accessing the config might not be so easy. 

@pawamoy Do you think that addin `std` alongside `py` could be ok?

**Comment by pawamoy** [comment]
Added docs about `domains`.
