### ISSUE TITLE
Relative links are striping default url fragments and thus not working correctly

### ISSUE THREAD

**Issue by Kigstn** [mkdocstrings/mkdocstrings#556]
**Please open an issue on [Griffe](https://github.com/mkdocstrings/griffe/issues) (new Python handler)
or [pytkdocs](https://github.com/mkdocstrings/pytkdocs/issues) (legacy Python handler) instead
if this is related to Python docstrings parsing or the collection of Python objects!**

**Describe the bug**
Hey! Not quite sure if this is an mkdocs, mkdocstrings, griffe, or readthedocs problem - hope this is the right place :)

Currently putting links to different pages in the docs produces the wrong url.

*Example:*
```
Here is a [link to a guide](/guides/basic)
```
should link to `URL/guides/basic`. It does that, but not correctly as it strips default url fragements such as RTDs `.../en/latest/...`. This leads to broken links as you can see here (bottom three links): https://bungio.readthedocs.io/en/stable/

I used autorefs to fix the problem, you can see the correct links here: https://bungio.readthedocs.io/en/latest/
Commit which fixed the issue: https://github.com/Kigstn/BungIO/commit/cea594814a51bb945a7ba2ce86490f11bf5433bb

**To Reproduce**
1. Host on RTD
2. Use markdows hyperlink to link to a relative file location
3. Generated link misses the  `.../en/latest/...`.

**Expected behavior**

 `.../en/latest/...` is incuded in the link

**Screenshots**
![image](https://user-images.githubusercontent.com/38250010/232321414-e5f47f17-87a0-4618-aeab-cc7f0d577008.png)

**Information (please complete the following information):**
- OS: [None]
- Browser: [all]
- `mkdocstrings` version: [0.18.1] 

**Additional context**

**Comment by pawamoy** [comment]
Hello! Unfortunately this is not the right place (it's more a question for MkDocs), but that's OK :slightly_smiling_face: 
IMO this behavior is expected. When you link to something by starting with a slash, it builds the URL relative to the root (domain). If you want to keep the fragments that are added by the SSG or the server, you must use relative URLs.

So instead of 

```
Here is a [link to a guide](/guides/basic)
```

try to do

```
Here is a [link to a guide](../guides/basic)
```

The relative path must then be adapted because it depends on the URL of the page showing it.

Nothing actionable here for mkdocstrings, closing!
