### ISSUE TITLE
Question regarding injecting DocStrings

### ISSUE THREAD

**Issue by phil65** [mkdocstrings/mkdocstrings#589]
Just trying to understand, from what scope can I insert DocStrings into my project?

This here works:

`::: logging.LogRecord`

or even:

`::: mkdocs.something_from_mkdocs`

but

`::: ast.AST`

(or anything else from ast module) gives "could not collect" error.

EDIT:

My guess would be: because MkDocStrings is using the AST for checking and ast.AST is imported via star operator?
( https://github.com/python/cpython/blob/main/Lib/ast.py#L29C15-L29C15 )

EDIT2:
... and `::: collections.OrderedDict` raises a different Exception, `jinja2.exceptions.TemplateNotFound: alias.html`

**Comment by pawamoy** [comment]
Hey, that's a very good question! This deserves an entry in the docs :slightly_smiling_face: 

The `::: ast.AST` case does not work, because the `AST` classes is imported from the private `_ast` module with a wildcard import, as you noted. And since we didn't [pre-load](https://mkdocstrings.github.io/python/usage/configuration/general/#preload_modules) the `_ast` module, or [allowed alias resolution to external modules](https://mkdocstrings.github.io/python/usage/#load_external_modules), all the wildcard imported objects are not detected. So when we try to access `ast.AST`, it fails because there's no `AST` member in `ast`. The error is propertly caught.

The `collections.OrderedDict` is almost the same, except that this time `OrderedDict` is imported directly (without a wildcard import), so the alias exist but cannot be resolved, ending up with a "template not found alias.html". This error could probably be better handled.

In the end, you can solve this by adding this line to your Python handler options, in mkdocs.yml: `preload_modules: [_ast, _collections]`. Also, we could consider always resolving to external modules **if** they are the private equivalent of the source module: if `collections.OrderedDict` -> `_collections.OrderedDict` then resolve.

**Comment by phil65** [comment]
Okay, thank you for the detailed explanation. The last detail I dont understand: OrderedDict is imported  explicitely. Why doesnt it work in that case? Because it´s placed in an exception block and therefore not at root level of the AST tree?

**Comment by pawamoy** [comment]
It does not work because it is imported from `_collections`, which is not loaded.

- `collections.OrderedDict` points to `_collections.OrderedDict`
- `_collections` is not loaded, so `collections.OrderedDict` cannot be resolved (stays an alias)
- mkdocstrings fails with "no template alias.html"

Let me know if this is still unclear :slightly_smiling_face:

**Comment by phil65** [comment]
One more question if you dont mind, in case you are familiar with the following plugin. 😄
When I am inside a [MkDocs-Gen-Files](https://github.com/oprypin/mkdocs-gen-files) script and I am importing modules there, does that make them "preloaded" for MkDocStrings?

**Comment by pawamoy** [comment]
No, the preloading feature has nothing to do with modules being imported or not. By "loaded" we mean "loaded by Griffe". To pre-load a module, you have to use the [`preload_modules` option](https://mkdocstrings.github.io/python/usage/configuration/general/#preload_modules) option :slightly_smiling_face:  It acts as an include-list. If you want to resolve everything, always, you can use the [`load_external_modules` option](https://mkdocstrings.github.io/python/usage/#load_external_modules), though be careful of the side-effects (explained in the docs).

**Comment by pawamoy** [comment]
Griffe now automatically resolve aliases pointing to modules with the same name but private, for example:

- `ast` -> `_ast`
- `collections` -> `_collections`
- etc.

So I believe this issue can be closed :relaxed:
