### ISSUE TITLE
bug: Doctest formatting

### ISSUE THREAD

**Issue by andreisorokin-astrazeneca** [mkdocstrings/mkdocstrings#659]
### Description of the bug
doctests formatting do not respec code lines

### To Reproduce
```python
class StreamFromIter(io.RawIOBase):
    """Stream bytes from iterable/iterator.

    >>> def chunks():
    ...     for chunk in [b"foo", b"bar", b"spam"]:
    ...         yield chunk
    >>> with io.BufferedReader(StreamFromIter(chunks())) as stream:
    ...     print(stream.read())
    b'foobarspam'
    >>> with StreamFromIter([b"foo", b"bar", b"spam"]) as stream:
    ...     print(stream.read())
    b'foobarspam'
    """
```
formatted as

```
def chunks(): ... for chunk in [b"foo", b"bar", b"spam"]: ... yield chunk with io.BufferedReader(StreamFromIter(chunks())) as stream: ... print(stream.read()) b'foobarspam' with StreamFromIter([b"foo", b"bar", b"spam"]) as stream: ... print(stream.read()) b'foobarspam'
```

### Full traceback
N/A

### Expected behavior
doctest formated as code

### Environment information
- __System__: macOS-14.3.1-arm64-arm-64bit
- __Python__: cpython 3.11.6
- __Environment variables__:
- __Installed packages__:
  - `mkdocstrings` v0.24.1

### Additional context
N/A

**Comment by pawamoy** [comment]
Thanks for the report. Such pycon code blocks without fences (triple backticks) are only recognized by our parser in Examples sections. If you want it to be recognized everywhere, you can use [Markdown PyCon](https://pawamoy.github.io/markdown-pycon/), which is currently only available to sponsors and will be released to the public when the [1000$/month funding goal](https://pawamoy.github.io/insiders/#1000-gravifridge-fluid-renewal) is reached :slightly_smiling_face: 

You can also simply wrap those in code blocks:

```python
class StreamFromIter(io.RawIOBase):
    """Stream bytes from iterable/iterator.

    ```pycon
    >>> def chunks():
    ...     for chunk in [b"foo", b"bar", b"spam"]:
    ...         yield chunk
    >>> with io.BufferedReader(StreamFromIter(chunks())) as stream:
    ...     print(stream.read())
    b'foobarspam'
    >>> with StreamFromIter([b"foo", b"bar", b"spam"]) as stream:
    ...     print(stream.read())
    b'foobarspam'
    ```
    """
```

Since there are solutions already available, I will close this, but feel free to comment further!
